## A static utility for generating a GDScript file containing gameplay tag constants.
##
## Takes an array of registered StringName tags and outputs a static class 
## file with safe constants, enabling IDE autocomplete for tag references.
##
## @meta_addon: GodotGAS 1.0
## @meta_author: YulRun (https://YulRun.Dev)
## @meta_license: MIT

@tool
@icon("res://addons/GodotGAS/icons/godot_gas_asc.svg")
class_name GameplayTagGenerator extends RefCounted

## The target file path where the generated tag constants script will be saved.
const GENERATED_FILE_PATH = "res://addons/GodotGAS/data/gameplay_tags.gd"


#region Code Generation
## Takes an array of tags and writes a static class file with constants for IDE autocomplete.
static func generate_tags_file(tags: Array[StringName]) -> void:
	var file = FileAccess.open(GENERATED_FILE_PATH, FileAccess.WRITE)
	if not file:
		printerr("GodotGAS: Failed to open path for tag generation: ", GENERATED_FILE_PATH)
		return

	# Write standard header warning so users don't manually edit it
	file.store_line("## AUTO-GENERATED BY GodotGAS PLUGIN. DO NOT EDIT MANUALLY.")
	file.store_line("##")
	file.store_line("## Used for accessing StringName references to Gameplay Tags in Scripts.")
	file.store_line("##")
	file.store_line("## @meta_addon: GodotGAS 1.0")
	file.store_line("## @meta_author: YulRun (https://YulRun.Dev)")
	file.store_line("## @meta_license: MIT")
	file.store_line("")
	file.store_line("@tool")
	file.store_line("class_name GameplayTags")
	file.store_line("")

	for tag in tags:
		var tag_string = String(tag)
		
		# Convert hierarchy dots into underscores for valid variable names
		var constant_name = tag_string.replace(".", "_")
		
		# Ensure the generated name is safe from special characters or numbers at the start
		constant_name = _sanitize_identifier(constant_name)
		
		# Write the constant line to the file
		file.store_line("const %s: StringName = &\"%s\"" % [constant_name, tag_string])

	file.close()
	print("GodotGAS: Successfully generated gameplay_tags.gd with %d constants." % tags.size())
#endregion


#region Helpers
## Internally sanitizes a string to ensure it forms a valid GDScript identifier.
static func _sanitize_identifier(id: String) -> String:
	# Replace anything that isn't alphanumeric or underscore with an underscore
	var regex = RegEx.new()
	regex.compile("[^a-zA-Z0-9_]")
	var sanitized = regex.sub(id, "_", true)
	
	# GDScript identifiers can't start with a number
	if sanitized.length() > 0 and sanitized[0].is_valid_int():
		sanitized = "_" + sanitized
		
	return sanitized
#endregion
