## AUTO-GENERATED BY GodotGAS PLUGIN. DO NOT EDIT MANUALLY.
##
## Used for accessing StringName references to Gameplay Tags in Scripts.
##
## @meta_addon: GodotGAS
## @meta_author: YulRun (https://YulRun.Dev)
## @meta_license: MIT

@tool
class_name GameplayTags

const Ability_Basic_Damage: StringName = &"Ability.Basic.Damage"
const Ability_Basic_Heal: StringName = &"Ability.Basic.Heal"
const Ability_Channeled_Beam: StringName = &"Ability.Channeled.Beam"
const Ability_Combat_Explosion: StringName = &"Ability.Combat.Explosion"
const Ability_Combat_Shoot: StringName = &"Ability.Combat.Shoot"
const Cooldown_Beam: StringName = &"Cooldown.Beam"
const Cooldown_Damage: StringName = &"Cooldown.Damage"
const Cooldown_Heal: StringName = &"Cooldown.Heal"
const Cooldown_Shoot: StringName = &"Cooldown.Shoot"
const Cue_Aura_Shield: StringName = &"Cue.Aura.Shield"
const Cue_Impact_Explosion: StringName = &"Cue.Impact.Explosion"
const Cue_Impact_Hit: StringName = &"Cue.Impact.Hit"
const Event_Combat_Hit: StringName = &"Event.Combat.Hit"
const State_Movement_Sprint: StringName = &"State.Movement.Sprint"
const State_Turnbased_Active: StringName = &"State.Turnbased.Active"
const Status_Buff_Shielded: StringName = &"Status.Buff.Shielded"
const Status_Debuff_Burning: StringName = &"Status.Debuff.Burning"
const Status_Debuff_Chilled: StringName = &"Status.Debuff.Chilled"
const Status_Debuff_Frozen: StringName = &"Status.Debuff.Frozen"
const Status_Debuff_Silenced: StringName = &"Status.Debuff.Silenced"
const Status_Debuff_Stunned: StringName = &"Status.Debuff.Stunned"
